FROM golang:1.26 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /scheduler-webhook ./cmd/scheduler-webhook

FROM alpine:latest

COPY --from=builder /scheduler-webhook /scheduler-webhook

ENTRYPOINT ["/scheduler-webhook"]
