apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fake-gpu-device-plugin
  namespace: kube-system
  labels:
    app: fake-gpu-device-plugin
spec:
  selector:
    matchLabels:
      app: fake-gpu-device-plugin
  template:
    metadata:
      labels:
        app: fake-gpu-device-plugin
    spec:
      priorityClassName: system-node-critical
      containers:
        - name: fake-gpu-device-plugin
          image: fake-gpu-device-plugin:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins